version: "3"

#could use working_dir for specifying base dir and avoid relative paths inside each container

services:
  nginx-proxy:  
    image: tekn0ir/nginx-stream
    ports:   
      - ${REVERSE_PROXY_EXTERNAL_PORT}:${REVERSE_PROXY_INTERNAL_PORT}
      - "8082:8082"
    volumes:
      - ./backend/reverse-proxy/conf/stream:/opt/nginx/stream.conf.d
      - ./backend/reverse-proxy/conf/http:/opt/nginx/http.conf.d
    networks:
      - backend

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - /backend/mqtt-broker/log:/mosquitto/log
      - /backend/mqtt-broker/data/:/mosquitto/data
      - ./backend/mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - ${MQTT_BROKER_MQTT_EXTERNAL_PORT}:${MQTT_BROKER_MQTT_INTERNAL_PORT}
    #  - ${MQTT_BROKER_WEBSOCKET_EXTERNAL_PORT}:${MQTT_BROKER_WEBSOCKER_INTERNAL_PORT} not used
    depends_on:
      - nginx-proxy
    networks:
      - backend

networks:
  backend:
  frontend:

