version: "3"

#could not use working_dir for specifying base dir and avoid relative paths

services:
  nginx-proxy:
    image: nginx
    volumes:
      - /backend/reverse-proxy/templates:/etc/nginx/templates
    ports:
      - "${REVERSE_PROXY_PORT}:${REVERSE_PROXY_INTERNAL_PORT}"
    networks:
      - backend

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - /backend/mosquitto-broker/log:/mosquitto/log
      - /backend/mosquitto-broker/data/:/mosquitto/data
      - /backend/mosquitto-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - ${MQTT_BROKER_MQTT_PORT}:${MQTT_BROKER_MQTT_INTERNAL_PORT}
      - ${MQTT_BROKER_WEBSOCKET_PORT}:${MQTT_BROKER_WEBSOCKER_INTERNAL_PORT}
    depends_on:
      - nginx-proxy
    networks:
      - backend

  networks:
      - backend
      - frontend


