FROM node:18.8.0-alpine


# Create microservice directory
WORKDIR /usr/src/users

VOLUME /var/log/nginx

# Install microservice dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

#to fix https://github.com/microsoft/WSL/issues/14
RUN npm config set unsafe-perm=true
RUN npm install

# Bundle microservice source
COPY . .


CMD [ "npm", "run", "start" ]