const mongoose = require("mongoose");

const profileSchema = mongoose.Schema(
  {
    _id: {
      type: String,
      required: true,
    }, //the one generated by supabase (they suggest to do so)
    email: {
      //added
      type: String,
      unique: true, // `email` must be unique
    },
    name: {
      type: String,
      required: true,
    },
    surname: {
      type: String,
      required: true,
    },
    gender: {
      type: String,
    },
    language: {
      type: String,
    },
    city: {
      //added
      type: String,
    },
    country: {
      //added
      type: String,
    },
    profilePictureUri: {
      type: String,
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
    updatedAt: {
      type: Date,
      default: Date.now,
    },
    lastLoginAt: {
      type: Date,
      default: Date.now,
    },
    unlockedAchievements: [{ type: String }], //the achievements' ids
    ecoScore: {
      type: Number,
      default: 0, //before a trip is made it must be visualizable anyway
    },
    level: {
      type: Number,
      default: 0, //before a trip is made it must be visualizable anyway
    },
  },
  { _id: false }
);

module.exports = mongoose.model("users", profileSchema);
//vehicles: [{ type: String }], //actually can put this association in vehicles since I must fetch from it too
