const { validateToken } = require("../middlewares/auth");

const authenticateAndSaveUserId = async (socket, next) => {
  if (socket.handshake.query && socket.handshake.query.token) {
    await validateToken(access_token)
      .then((access_token) => {
        socket.decoded = access_token;
      })
      .catch((err) => {
        //if tokenUserId is not generated by supabase: interaction with backend CAN'T go on
        socket.decoded = null;
      });

    if (socket.decoded) {
      next();
      return;
    }
  }
  next(new Error("Authentication error"));
};

module.exports = authenticateAndSaveUserId;
