const { validateToken } = require("../middlewares/auth");

const authenticate = async (socket, next) => {
  //
  if (socket.handshake.query && socket.handshake.query.token) {
    await validateToken(access_token).catch((err) => {
      //if tokenUserId is not generated by supabase: interaction with backend CAN'T go on
      socket.decoded = null;
    });

    if (socket.decoded) {
      next();
      return;
    }
  }
  next(new Error("Authentication error"));
};
