const { validateToken } = require("../middlewares/auth");

const authenticateAndSaveUserId = async (socket, next) => {
  console.log("checking authentication for socket");
  if (socket.handshake.query && socket.handshake.query.token) {
    console.log("token present");
    await validateToken(socket.handshake.query.token)
      .then((user) => {
        socket.userId = user.id;
      })
      .catch((err) => {
        //if tokenUserId is not generated by supabase: interaction with backend CAN'T go on
        socket.userId = null;
      });

    if (socket.userId) {
      console.log(
        "[backend] socket correctly authenticated...(id: ",
        socket.userId,
        ") passing request through..."
      );
      next();

      return;
    }
  }
  console.log("[backend] socket not authenticated... sending error");
  next(new Error("Authentication error"));
};

module.exports = { authenticateAndSaveUserId };
